services:
  next:
    container_name: next
    restart: always
    image: chaty:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - chaty_nginx_proxy
    enviroment: 
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
  nginx:
    container_name: nginx
    restart: always
    image: chaty_nginx:latest
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - next
    networks:
      - chaty_nginx_proxy

networks:
  chaty_nginx_proxy:
    external:
      name: chaty_nginx_proxy
